### ISSUE TITLE
bind source path does not exist

### ISSUE THREAD

**Issue by henkvancann** [peacekeeper/did-webs-iiw-tutorial#2]
Following the README.md install guide, I bumped into this error, I could solve by hand.
I'm on Mac OS 13.6
"
Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /Users/hvc/apps/did-webs-iiw37-tutorial/volume/dkr/did_json
"
My try:
mkdir /Users/hvc/apps/did-webs-iiw37-tutorial/volume/dkr/did_json 

But then:
did-webs-iiw37-tutorial ➤ docker compose up -d                                                                                                                            git:main
[+] Running 0/0
 ⠋ Container dkr                       Creating                                                                                                                               0.0s
 ⠋ Container 45bdf3c73d53_witnesshost  Recreate                                                                                                                               0.0s
Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /Users/hvc/apps/did-webs-iiw37-tutorial/volume/dkr/keri_cesr
did-webs-iiw37-tutorial ➤ mkdir /Users/hvc/apps/did-webs-iiw37-tutorial/volume/dkr/keri_cesr                                                                              git:main
did-webs-iiw37-tutorial ➤ docker compose up -d                                                                                                                            git:main
[+] Running 1/0
 ⠿ Container dkr                                    Created                                                                                                                   0.1s
 ⠋ Container 45bdf3c73d53_45bdf3c73d53_witnesshost  Recreate                                                                                                                  0.1s
Error response from daemon: Duplicate mount point: /keripy/scripts/keri/cf/main/
did-webs-iiw37-tutorial ➤ cd /Users/hvc/apps/did-webs-iiw37-tutorial/volume/dkr/keri_cesr

**Comment by peacekeeper** [comment]
Hmm may be some Mac-specific issue, I don't really know about that.. @2byrds do you have an idea maybe?

**Comment by 2byrds** [comment]
Sorry I haven't seen that one on my Mac :(

**Comment by 2byrds** [comment]
These are my Mac setting changes https://github.com/peacekeeper/did-webs-iiw37-tutorial/commit/337b4a0dbd41d1fd6ff3d7c0ba536fd3ad4aa44e

**Comment by peacekeeper** [comment]
@henkvancann When you get "Duplicate mount point", please try to first run `docker-compose down` to shut down the containers, before you launch them again.

Let us know if that helps!

**Comment by henkvancann** [comment]
It did, thx, I have to brush up my Docker knowledge, for sure!

**Comment by peacekeeper** [comment]
@henkvancann I also pushed another commit that should make sure you don't have to create the paths manually. Maybe try to delete everything and start from the beginning with a fresh copy of the repo, to see if it works now?

**Comment by henkvancann** [comment]
I'll try this, later today and onwards, and report back with some textual exception handling in a PR for people that'll come after me.
For now, I am good :
"
Loading 3 OOBIs...
http://witnesshost:5642/oobi/BBilc4-L3tFUnfM_wJr4S4OJanAv_VmF_dJNN6vkf2Ha/controller succeeded
http://witnesshost:5643/oobi/BLskRTInXnMxWaGqcpSyMgo0nYbalW99cGZESrz3zapM/controller succeeded
http://witnesshost:5644/oobi/BIKKuvBwpmDVA4Ds-EpL5bt9OqPzWPja2LigFYZN2YfX/controller succeeded
Waiting for witness receipts...
Prefix  EC3ezCFPyDg-rvIKrot7CJne8DMkJtNLazCBh9j3GZaN
	Public key 1:  DDekA3yJniYleMENmbxZp5jU976dflo7v4UBQyIRwXTm
	"

**Comment by henkvancann** [comment]
The next command:

bash-5.1# dkr did webs generate --name controller --did did:webs:[YOUR COLON-SEPARATED DOMAIN+/-PATH+/-PORT]:[YOUR AID] --oobi http://witnesshost:[MATCH CHOSEN WITNESS PORT]/oobi/[YOUR AID]/witness/[ONE OF YOUR WITNESSES]

`[YOUR COLON-SEPARATED DOMAIN+/-PATH+/-PORT]` means you can _optionally_ add a PATH and/or PORT.

My question: 
[ONE OF YOUR WITNESSES] -> can I just select one of the three randomly?

**Comment by 2byrds** [comment]
Yes, any witness

**Comment by henkvancann** [comment]
Done
