### ISSUE TITLE
dkr did webs resolve  fails where the did keri with oobi succeeds

### ISSUE THREAD

**Issue by henkvancann** [peacekeeper/did-webs-iiw-tutorial#3]
bash-5.1# dkr did keri resolve --name controller --did did:keri:ENbWS51Pw1rmxz5QIfK5kp3ODaEeQcZjqQNrLpc6mMQq --oobi http://witnesshost:5642/oobi/ENbWS51Pw1rmxz5QIfK5kp3ODaEeQcZjqQNrLpc6mMQq/witness/BBilc4-L3tFUnfM_wJr4S4OJanAv_VmF_dJNN6vkf2Ha

From arguments got aid: ENbWS51Pw1rmxz5QIfK5kp3ODaEeQcZjqQNrLpc6mMQq
From arguments got oobi: http://witnesshost:5642/oobi/ENbWS51Pw1rmxz5QIfK5kp3ODaEeQcZjqQNrLpc6mMQq/witness/BBilc4-L3tFUnfM_wJr4S4OJanAv_VmF_dJNN6vkf2Ha
{
  "id": "did:keri:ENbWS51Pw1rmxz5QIfK5kp3ODaEeQcZjqQNrLpc6mMQq",
  "verificationMethod": [
    {
      "id": "#DH9FyLXMEKr_faZhnBvuCy02J9crkNgCcgDSqkrFki_o",
      "type": "JsonWebKey",
      "controller": "did:keri:ENbWS51Pw1rmxz5QIfK5kp3ODaEeQcZjqQNrLpc6mMQq",
      "publicKeyJwk": {
        "kid": "DH9FyLXMEKr_faZhnBvuCy02J9crkNgCcgDSqkrFki_o",
        "kty": "OKP",
        "crv": "Ed25519",
        "x": "f0XItcwQqv99pmGcG-4LLTYn1yuQ2AJyANKqSsWSL-g"
      }
    }
  ]
}
bash-5.1# dkr did webs resolve --name controller --did did:webs:github.com:weboftrust:WOT-terms:ENbWS51Pw1rmxz5QIfK5kp3ODaEeQcZjqQNrLpc6mMQq 
Loading DID Doc from http://github.com/weboftrust:WOT-terms/ENbWS51Pw1rmxz5QIfK5kp3ODaEeQcZjqQNrLpc6mMQq/did.json
Traceback (most recent call last):
  File "/usr/local/bin/dkr", line 33, in <module>
    sys.exit(load_entry_point('dkr', 'console_scripts', 'dkr')())
  File "/usr/local/var/did-keri-resolver/src/dkr/app/cli/dkr.py", line 32, in main
    raise ex
  File "/usr/local/var/did-keri-resolver/src/dkr/app/cli/dkr.py", line 29, in main
    directing.runController(doers=doers, expire=0.0)
  File "/usr/local/lib/python3.10/site-packages/keri/app/directing.py", line 665, in runController
    doist.do(doers=doers)
  File "/usr/local/lib/python3.10/site-packages/hio/base/doing.py", line 156, in do
    self.recur()  # increments .tyme runs recur context
  File "/usr/local/lib/python3.10/site-packages/hio/base/doing.py", line 275, in recur
    tock = dog.send(self.tyme)  # yielded tock == 0.0 means re-run asap
  File "/usr/local/lib/python3.10/site-packages/hio/base/doing.py", line 922, in do
    self.done = self.recur(tyme=tyme)  # equv of doist.recur
  File "/usr/local/lib/python3.10/site-packages/hio/base/doing.py", line 1026, in recur
    tock = dog.send(tyme)  # yielded tock == 0.0 means re-run asap
  File "/usr/local/var/did-keri-resolver/src/dkr/app/cli/commands/did/webs/resolve.py", line 67, in resolve
    dd_actual = didding.fromDidWeb(json.loads(self.loadUrl(dd_url).decode("utf-8")))
  File "/usr/local/var/did-keri-resolver/src/dkr/app/cli/commands/did/webs/resolve.py", line 99, in loadUrl
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://github.com/weboftrust:WOT-terms/ENbWS51Pw1rmxz5QIfK5kp3ODaEeQcZjqQNrLpc6mMQq/did.json
bash-5.1#

**Comment by peacekeeper** [comment]
The URL http://github.com/weboftrust:WOT-terms/ENbWS51Pw1rmxz5QIfK5kp3ODaEeQcZjqQNrLpc6mMQq/did.json doesn't exist. You probably have to turn on Github pages, make sure the file is hosted at the right location, and adjust the DID to match that location.

**Comment by henkvancann** [comment]
Github pages is on. And the cesr is verifiable from that location (with an oobi) However I was testing the root directory and I've now added the AID as a directory, just like you did.

Could it be related to this in the command:
`dkr did webs resolve --name controller --did did:webs:github.com:weboftrust/WOT-terms:ENbWS51Pw1rmxz5QIfK5kp3ODaEeQcZjqQNrLpc6mMQq`

versus 
`dkr did webs resolve --name controller --did did:webs:github.com:weboftrust:WOT-terms:ENbWS51Pw1rmxz5QIfK5kp3ODaEeQcZjqQNrLpc6mMQq
`
?

**Comment by henkvancann** [comment]
Hi Markus,

I can't get the thing going, unfortunately. Tried in two places github.com plain and in github pages. The one above and fully started anew with finally this one:

dkr did webs generate --name controller --did did:webs:weboftrust.github.io:WOT-terms:test:did-webs-iiw37-tutorial:EDc2kYoDYWrQow0v6fbKvOypYzj_Vi-UxbEQv0rWC1Kx --oobi http://witnesshost:5642/oobi/EDc2kYoDYWrQow0v6fbKvOypYzj_Vi-UxbEQv0rWC1Kx/witness/BBilc4-L3tFUnfM_wJr4S4OJanAv_VmF_dJNN6vkf2Ha

I uploaded the did.json and keri.cesr files using git and 
https://github.com/WebOfTrust/WOT-terms/actions/runs/6539136450 ran succesfully.

So I expect did:webs to "run" (whatever that might be, I'd like to be able to get the DID docs and verify the cesr file.): 
https://weboftrust.github.WOT-terms/test/did-webs-iiw37-tutorial/EDc2kYoDYWrQow0v6fbKvOypYzj_Vi-UxbEQv0rWC1Kx/did.json
Page not found in Docusaurus (understandable, DS interprets everything and builds a site)
So I try:
https://github.com/WebOfTrust/WOT-terms/blob/main/docs/test/did-webs-iiw37-tutorial/EDc2kYoDYWrQow0v6fbKvOypYzj_Vi-UxbEQv0rWC1Kx/did.json
And I get the plain source file. But wouldn't know what next.

Same with keri.cesr file.

I've offered a PR: https://github.com/peacekeeper/did-webs-iiw37-tutorial/pull/4, You don't have to accept it, but it documents the hurdles you run into when trying to run the demo as a rookie.

**Comment by henkvancann** [comment]
Because I get the plain source file delivered on github.com, I expect it to be in the right spot on the github.io github page:

bash-5.1# dkr did webs resolve --name controller --did did:webs:weboftrust.github.io:WOT-terms:test:did-webs-iiw37-tutorial:EDc2kYoDYWrQow0v6fbKvOypYzj_Vi-UxbEQv0rWC1Kx 
Loading DID Doc from http://weboftrust.github.io/WOT-terms:test:did-webs-iiw37-tutorial/EDc2kYoDYWrQow0v6fbKvOypYzj_Vi-UxbEQv0rWC1Kx/did.json
Traceback (most recent call last):
  File "/usr/local/bin/dkr", line 33, in <module>
    sys.exit(load_entry_point('dkr', 'console_scripts', 'dkr')())
  File "/usr/local/var/did-keri-resolver/src/dkr/app/cli/dkr.py", line 32, in main
    raise ex
  File "/usr/local/var/did-keri-resolver/src/dkr/app/cli/dkr.py", line 29, in main
    directing.runController(doers=doers, expire=0.0)
  File "/usr/local/lib/python3.10/site-packages/keri/app/directing.py", line 665, in runController
    doist.do(doers=doers)
  File "/usr/local/lib/python3.10/site-packages/hio/base/doing.py", line 156, in do
    self.recur()  # increments .tyme runs recur context
  File "/usr/local/lib/python3.10/site-packages/hio/base/doing.py", line 275, in recur
    tock = dog.send(self.tyme)  # yielded tock == 0.0 means re-run asap
  File "/usr/local/lib/python3.10/site-packages/hio/base/doing.py", line 922, in do
    self.done = self.recur(tyme=tyme)  # equv of doist.recur
  File "/usr/local/lib/python3.10/site-packages/hio/base/doing.py", line 1026, in recur
    tock = dog.send(tyme)  # yielded tock == 0.0 means re-run asap
  File "/usr/local/var/did-keri-resolver/src/dkr/app/cli/commands/did/webs/resolve.py", line 67, in resolve
    dd_actual = didding.fromDidWeb(json.loads(self.loadUrl(dd_url).decode("utf-8")))
  File "/usr/local/var/did-keri-resolver/src/dkr/app/cli/commands/did/webs/resolve.py", line 99, in loadUrl
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://weboftrust.github.io/WOT-terms:test:did-webs-iiw37-tutorial/EDc2kYoDYWrQow0v6fbKvOypYzj_Vi-UxbEQv0rWC1Kx/did.json
bash-5.1# 

The tool seems to mess up the path, but I don't know

**Comment by henkvancann** [comment]
THIS BUGGER WORKS FINE:
bash-5.1# dkr did keri resolve --name controller --did did:keri:EDc2kYoDYWrQow0v6fbKvOypYzj_Vi-UxbEQv0rWC1Kx --oobi http://witnesshost:5642/oobi/EDc2kYoDYWrQow0v6fbKvOypYzj_Vi-UxbEQv0rWC1Kx/witness/BBilc4-L3tFUnfM_wJr4S4OJanAv_VmF_dJNN6vkf2Ha
From arguments got aid: EDc2kYoDYWrQow0v6fbKvOypYzj_Vi-UxbEQv0rWC1Kx
From arguments got oobi: http://witnesshost:5642/oobi/EDc2kYoDYWrQow0v6fbKvOypYzj_Vi-UxbEQv0rWC1Kx/witness/BBilc4-L3tFUnfM_wJr4S4OJanAv_VmF_dJNN6vkf2Ha
{
  "id": "did:keri:EDc2kYoDYWrQow0v6fbKvOypYzj_Vi-UxbEQv0rWC1Kx",
  "verificationMethod": [
    {
      "id": "#DGPgvyX-rK7FTPZSCrXQALLgPRZRIOqBjQX4fqjuQ-Lt",
      "type": "JsonWebKey",
      "controller": "did:keri:EDc2kYoDYWrQow0v6fbKvOypYzj_Vi-UxbEQv0rWC1Kx",
      "publicKeyJwk": {
        "kid": "DGPgvyX-rK7FTPZSCrXQALLgPRZRIOqBjQX4fqjuQ-Lt",
        "kty": "OKP",
        "crv": "Ed25519",
        "x": "Y-C_Jf6srsVM9lIKtdAAsuA9FlEg6oGNBfh-qO5D4u0"
      }
    }
  ]
}
bash-5.1#

**Comment by peacekeeper** [comment]
@henkvancann Before you try to resolve any `did:webs`, you have to make sure that your `did.json` and` keri.cesr` files are uploaded correctly and accessible as plain files (not Github source viewer) at public URLs. Do you have such URLs, if yes, what are they?

If you can't reach those files anywhere, then probably there's something wrong with your Github pages, or Docusaurus (I don't know what that is).

**Comment by henkvancann** [comment]
Source viewer:

https://github.com/WebOfTrust/WOT-terms/blob/main/docs/test/did-webs-iiw37-tutorial/EDc2kYoDYWrQow0v6fbKvOypYzj_Vi-UxbEQv0rWC1Kx/did.json

https://github.com/WebOfTrust/WOT-terms/blob/main/docs/test/did-webs-iiw37-tutorial/EDc2kYoDYWrQow0v6fbKvOypYzj_Vi-UxbEQv0rWC1Kx/keri.cesr

What would their raw alternatives be? This?

https://raw.githubusercontent.com/WebOfTrust/WOT-terms/main/docs/test/did-webs-iiw37-tutorial/EDc2kYoDYWrQow0v6fbKvOypYzj_Vi-UxbEQv0rWC1Kx/did.json

https://raw.githubusercontent.com/WebOfTrust/WOT-terms/main/docs/test/did-webs-iiw37-tutorial/EDc2kYoDYWrQow0v6fbKvOypYzj_Vi-UxbEQv0rWC1Kx/keri.cesr

**Comment by henkvancann** [comment]
> @henkvancann Before you try to resolve any `did:webs`, you have to make sure that your `did.json` and` keri.cesr` files are uploaded correctly and accessible as plain files (not Github source viewer) at public URLs. Do you have such URLs, if yes, what are they?
> 
> If you can't reach those files anywhere, then probably there's something wrong with your Github pages, or Docusaurus (I don't know what that is).

Docusaurus.io is a technical documentation site generator. We run KERISSE.org on it.

**Comment by peacekeeper** [comment]
These won't work, because they show the Github source viewer, not the files themselves.

I imagine it would be something like `https://WebOfTrust.github.io/WOT-terms/...something`, but that's really up to your Github Pages configuration.

**Comment by henkvancann** [comment]
What would their raw alternatives be? This?

https://raw.githubusercontent.com/WebOfTrust/WOT-terms/main/docs/test/did-webs-iiw37-tutorial/EDc2kYoDYWrQow0v6fbKvOypYzj_Vi-UxbEQv0rWC1Kx/did.json

https://raw.githubusercontent.com/WebOfTrust/WOT-terms/main/docs/test/did-webs-iiw37-tutorial/EDc2kYoDYWrQow0v6fbKvOypYzj_Vi-UxbEQv0rWC1Kx/keri.cesr

**Comment by henkvancann** [comment]
bash-5.1# dkr did webs resolve --name controller --did did:webs:raw.githubusercontent.com:WOT-terms:test:did-webs-iiw37-tutorial:EDc2kYoDYWrQow0v6fbKvOypYzj_Vi-UxbEQv0rWC1Kx
Loading DID Doc from http://raw.githubusercontent.com/WOT-terms:test:did-webs-iiw37-tutorial/EDc2kYoDYWrQow0v6fbKvOypYzj_Vi-UxbEQv0rWC1Kx/did.json
Traceback (most recent call last):
  File "/usr/local/bin/dkr", line 33, in <module>
    sys.exit(load_entry_point('dkr', 'console_scripts', 'dkr')())
  File "/usr/local/var/did-keri-resolver/src/dkr/app/cli/dkr.py", line 32, in main
    raise ex
  File "/usr/local/var/did-keri-resolver/src/dkr/app/cli/dkr.py", line 29, in main
    directing.runController(doers=doers, expire=0.0)
  File "/usr/local/lib/python3.10/site-packages/keri/app/directing.py", line 665, in runController
    doist.do(doers=doers)
  File "/usr/local/lib/python3.10/site-packages/hio/base/doing.py", line 156, in do
    self.recur()  # increments .tyme runs recur context
  File "/usr/local/lib/python3.10/site-packages/hio/base/doing.py", line 275, in recur
    tock = dog.send(self.tyme)  # yielded tock == 0.0 means re-run asap
  File "/usr/local/lib/python3.10/site-packages/hio/base/doing.py", line 922, in do
    self.done = self.recur(tyme=tyme)  # equv of doist.recur
  File "/usr/local/lib/python3.10/site-packages/hio/base/doing.py", line 1026, in recur
    tock = dog.send(tyme)  # yielded tock == 0.0 means re-run asap
  File "/usr/local/var/did-keri-resolver/src/dkr/app/cli/commands/did/webs/resolve.py", line 67, in resolve
    dd_actual = didding.fromDidWeb(json.loads(self.loadUrl(dd_url).decode("utf-8")))
  File "/usr/local/var/did-keri-resolver/src/dkr/app/cli/commands/did/webs/resolve.py", line 99, in loadUrl
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://raw.githubusercontent.com/WOT-terms:test:did-webs-iiw37-tutorial/EDc2kYoDYWrQow0v6fbKvOypYzj_Vi-UxbEQv0rWC1Kx/did.json
bash-5.1# 

Now I got the raw content, it still messes up this URL in the last line:
`Bad Request for url: https://raw.githubusercontent.com/WOT-terms:test:did-webs-iiw37-tutorial/EDc2kYoDYWrQow0v6fbKvOypYzj_Vi-UxbEQv0rWC1Kx/did.json `

should at least be? `url: https://raw.githubusercontent.com/WOT-terms/test/did-webs-iiw37-tutorial/EDc2kYoDYWrQow0v6fbKvOypYzj_Vi-UxbEQv0rWC1Kx/did.json`

**Comment by henkvancann** [comment]
> These won't work, because they show the Github source viewer, not the files themselves.
> 
> I imagine it would be something like `https://WebOfTrust.github.io/WOT-terms/...something`, but that's really up to your Github Pages configuration.

Maybe, but for now I have the raw files served in my hand and it messes up the URL (see report above 2x":" where it should be 2x "/"), so I don't think my Github pages config is the bottleneck here.

**Comment by peacekeeper** [comment]
@henkvancann I think you're right there's a bug that doesn't replace the `:` character with `/` in the http URL. I just opened a PR to fix this: https://github.com/hyperledger-labs/did-webs-resolver/pull/25

This only occurs if the path consists of multiple segments, which is probably why we didn't notice this.

In the meantime, you could try to publish the did.json and keri.cesr files at a URL that only has on path segment.

**Comment by henkvancann** [comment]
YESSS!!

bash-5.1# dkr did webs generate --name controller --did did:webs:raw.githubusercontent.com:WOT-terms:test:did-webs-iiw37-tutorial:EDc2kYoDYWrQow0v6fbKvOypYzj_Vi-UxbEQv0rWC1Kx --oobi http://witnesshost:5642/oobi/EDc2kYoDYWrQow0v6fbKvOypYzj_Vi-UxbEQv0rWC1Kx/witness/BBilc4-L3tFUnfM_wJr4S4OJanAv_VmF_dJNN6vkf2Ha
{
  "didDocument": {
    "id": "did:web:raw.githubusercontent.com:WOT-terms:test:did-webs-iiw37-tutorial:EDc2kYoDYWrQow0v6fbKvOypYzj_Vi-UxbEQv0rWC1Kx",
    "verificationMethod": [
      {
        "id": "#DGPgvyX-rK7FTPZSCrXQALLgPRZRIOqBjQX4fqjuQ-Lt",
        "type": "JsonWebKey",
        "controller": "did:web:raw.githubusercontent.com:WOT-terms:test:did-webs-iiw37-tutorial:EDc2kYoDYWrQow0v6fbKvOypYzj_Vi-UxbEQv0rWC1Kx",
        "publicKeyJwk": {
          "kid": "DGPgvyX-rK7FTPZSCrXQALLgPRZRIOqBjQX4fqjuQ-Lt",
          "kty": "OKP",
          "crv": "Ed25519",
          "x": "Y-C_Jf6srsVM9lIKtdAAsuA9FlEg6oGNBfh-qO5D4u0"
        }
      }
    ]
  },
  "pre": "EDc2kYoDYWrQow0v6fbKvOypYzj_Vi-UxbEQv0rWC1Kx",
  "state": {
    "vn": [
      1,
      0
    ],
    "i": "EDc2kYoDYWrQow0v6fbKvOypYzj_Vi-UxbEQv0rWC1Kx",
    "s": "0",
    "p": "",
    "d": "EDc2kYoDYWrQow0v6fbKvOypYzj_Vi-UxbEQv0rWC1Kx",
    "f": "0",
    "dt": "2023-10-16T20:12:35.525763+00:00",
    "et": "icp",
    "kt": "1",
    "k": [
      "DGPgvyX-rK7FTPZSCrXQALLgPRZRIOqBjQX4fqjuQ-Lt"
    ],
    "nt": "1",
    "n": [
      "EMnkAP7PmFsd8wLYKGCU8OHTHIRkmTMgNvLCGBE5EScs"
    ],
    "bt": "3",
    "b": [
      "BBilc4-L3tFUnfM_wJr4S4OJanAv_VmF_dJNN6vkf2Ha",
      "BLskRTInXnMxWaGqcpSyMgo0nYbalW99cGZESrz3zapM",
      "BIKKuvBwpmDVA4Ds-EpL5bt9OqPzWPja2LigFYZN2YfX"
    ],
    "c": [],
    "ee": {
      "s": "0",
      "d": "EDc2kYoDYWrQow0v6fbKvOypYzj_Vi-UxbEQv0rWC1Kx",
      "br": [],
      "ba": []
    },
    "di": ""
  },
  "kel": [
    {
      "ked": {
        "v": "KERI10JSON0001b7_",
        "t": "icp",
        "d": "EDc2kYoDYWrQow0v6fbKvOypYzj_Vi-UxbEQv0rWC1Kx",
        "i": "EDc2kYoDYWrQow0v6fbKvOypYzj_Vi-UxbEQv0rWC1Kx",
        "s": "0",
        "kt": "1",
        "k": [
          "DGPgvyX-rK7FTPZSCrXQALLgPRZRIOqBjQX4fqjuQ-Lt"
        ],
        "nt": "1",
        "n": [
          "EMnkAP7PmFsd8wLYKGCU8OHTHIRkmTMgNvLCGBE5EScs"
        ],
        "bt": "3",
        "b": [
          "BBilc4-L3tFUnfM_wJr4S4OJanAv_VmF_dJNN6vkf2Ha",
          "BLskRTInXnMxWaGqcpSyMgo0nYbalW99cGZESrz3zapM",
          "BIKKuvBwpmDVA4Ds-EpL5bt9OqPzWPja2LigFYZN2YfX"
        ],
        "c": [],
        "a": []
      },
      "stored": true,
      "signatures": [
        {
          "index": 0,
          "signature": "AAALEzHOlShNHt8ZNm6Pypx9vdf0az1gE-DhQRk5FVRafRskAEEQHhPVSqaO3YEN6mFKGpVkHnsOdAV1o72msR0G"
        }
      ],
      "witnesses": [
        "BBilc4-L3tFUnfM_wJr4S4OJanAv_VmF_dJNN6vkf2Ha",
        "BLskRTInXnMxWaGqcpSyMgo0nYbalW99cGZESrz3zapM",
        "BIKKuvBwpmDVA4Ds-EpL5bt9OqPzWPja2LigFYZN2YfX"
      ],
      "witness_signatures": [
        {
          "index": 0,
          "signature": "AAAZ6uuGuWEO19dMFy3kzPjhH5RTNc2LpmPsyWaY3hf8BBezezJr8Xbv6cxEGE-sR6of780nLjM0DJ8pdNJFLNgL"
        },
        {
          "index": 1,
          "signature": "ABBrxRkn9TIXWgCsZgLoyBfrAzA6KXRE3jOwb2DRveVi3DsySQAX3IMxEX07cg9aHCq-4SKGq3RBlZXrhN9bpw8F"
        },
        {
          "index": 2,
          "signature": "ACBbcceL2H725f1r-QVZkAmbvTb3yaVKKMsRlsGzAiDUtB6fg_q7vaQ2Aw5zG-pEexTTuFQP1ggaf4JfHtug4ukO"
        }
      ],
      "receipts": {},
      "timestamp": "2023-10-16T20:12:35.525763+00:00"
    }
  ]
}
bash-5.1#

**Comment by henkvancann** [comment]
Thx for the support. I think I also needed to regenerate the DID with the URL for the raw content. 
`
dkr did webs generate --name controller --did did:webs:raw.githubusercontent.com:WOT-terms:test:did-webs-iiw37-tutorial:EDc2kYoDYWrQow0v6fbKvOypYzj_Vi-UxbEQv0rWC1Kx --oobi http://witnesshost:5642/oobi/EDc2kYoDYWrQow0v6fbKvOypYzj_Vi-UxbEQv0rWC1Kx/witness/BBilc4-L3tFUnfM_wJr4S4OJanAv_VmF_dJNN6vkf2Ha
`
Which worked. So now I'll wait for the bug to be resolved and then run the did:webs resolve command again.

**Comment by peacekeeper** [comment]
@henkvancann I pushed new Docker images and updated the docker-compose.yml file to use the latest tag now:
https://github.com/peacekeeper/did-webs-iiw37-tutorial/commit/5365d2ff25a7c6fb8c624bc4d074c2810dfb8561

Could you maybe try again to resolve your `did:webs` using the latest image?

I think you should be able to resolve this DID:

```
did:webs:raw.githubusercontent.com:WebOfTrust:WOT-terms:main:docs:test:did-webs-iiw37-tutorial:EDc2kYoDYWrQow0v6fbKvOypYzj_Vi-UxbEQv0rWC1Kx
```

But I also still think it would be better to properly publish the files on Github Pages, instead of using the "raw.githubusercontent.com" URL.

**Comment by henkvancann** [comment]
> @henkvancann I pushed new Docker images and updated the docker-compose.yml file to use the latest tag now: [5365d2f](https://github.com/peacekeeper/did-webs-iiw37-tutorial/commit/5365d2ff25a7c6fb8c624bc4d074c2810dfb8561)
> 
> Could you maybe try again to resolve your `did:webs` using the latest image?
> 
> I think you should be able to resolve this DID:
> 
> ```
> did:webs:raw.githubusercontent.com:WebOfTrust:WOT-terms:main:docs:test:did-webs-iiw37-tutorial:EDc2kYoDYWrQow0v6fbKvOypYzj_Vi-UxbEQv0rWC1Kx
> ```
> 
> But I also still think it would be better to properly publish the files on Github Pages, instead of using the "raw.githubusercontent.com" URL.

Thx, will do! I think differently about the way I link to data publicly available on Github: imho it's irrelevant how I get it, it should verify if I do get it?

**Comment by henkvancann** [comment]
I think I need to generate a new AID, now that I've initiated a new Docker container session?

bash-5.1# dkr did webs resolve --name controller --did did:webs:raw.githubusercontent.com:WebOfTrust:WOT-terms:main:docs:test:did-webs-iiw37-tutorial:EDc2kYoDYWrQow0v6fbKvOypYzj_Vi-UxbEQv0rWC1Kx  ->

Keystore must already exist, exiting

**Comment by henkvancann** [comment]
Created a new AID and went through the process and worked. However I made a mistake when generating the DID doc so actually it doesn't verify, but hey, no worries for now:

bash-5.1# dkr did webs resolve --name controller --did did:webs:raw.githubusercontent.com:WebOfTrust:WOT-terms:main:docs:test:did-webs-iiw37-tutorial:EP1NLexo6s8Fk1R_jwOoUd24JN9DWVmF41xrJFpb8aBR
Loading DID Doc from http://raw.githubusercontent.com/WebOfTrust/WOT-terms/main/docs/test/did-webs-iiw37-tutorial/EP1NLexo6s8Fk1R_jwOoUd24JN9DWVmF41xrJFpb8aBR/did.json
Loading KERI CESR from http://raw.githubusercontent.com/WebOfTrust/WOT-terms/main/docs/test/did-webs-iiw37-tutorial/EP1NLexo6s8Fk1R_jwOoUd24JN9DWVmF41xrJFpb8aBR/keri.cesr
DID Doc does not verify
Comparing dictionaries:
expected:
{expected} 
and
 
actual:
{actual}
Comparing key id
Different values for key id: did:webs:raw.githubusercontent.com:WebOfTrust:WOT-terms:main:docs:test:did-webs-iiw37-tutorial:EP1NLexo6s8Fk1R_jwOoUd24JN9DWVmF41xrJFpb8aBR (expected) vs. did:webs:raw.githubusercontent.com:WOT-terms:test:did-webs-iiw37-tutorial:EP1NLexo6s8Fk1R_jwOoUd24JN9DWVmF41xrJFpb8aBR (actual)
Comparing key verificationMethod
Different values for key verificationMethod: [{'id': '#DFBTlnGd2gwTwMZTHIHUMmPxydvvXyXTOICWncIVS0oL', 'type': 'JsonWebKey', 'controller': 'did:webs:raw.githubusercontent.com:WebOfTrust:WOT-terms:main:docs:test:did-webs-iiw37-tutorial:EP1NLexo6s8Fk1R_jwOoUd24JN9DWVmF41xrJFpb8aBR', 'publicKeyJwk': {'kid': 'DFBTlnGd2gwTwMZTHIHUMmPxydvvXyXTOICWncIVS0oL', 'kty': 'OKP', 'crv': 'Ed25519', 'x': 'UFOWcZ3aDBPAxlMcgdQyY_HJ2-9fJdM4gJadwhVLSgs'}}] (expected) vs. [{'id': '#DFBTlnGd2gwTwMZTHIHUMmPxydvvXyXTOICWncIVS0oL', 'type': 'JsonWebKey', 'controller': 'did:webs:raw.githubusercontent.com:WOT-terms:test:did-webs-iiw37-tutorial:EP1NLexo6s8Fk1R_jwOoUd24JN9DWVmF41xrJFpb8aBR', 'publicKeyJwk': {'kid': 'DFBTlnGd2gwTwMZTHIHUMmPxydvvXyXTOICWncIVS0oL', 'kty': 'OKP', 'crv': 'Ed25519', 'x': 'UFOWcZ3aDBPAxlMcgdQyY_HJ2-9fJdM4gJadwhVLSgs'}}] (actual)
{
  "didDocument": null,
  "didResolutionMetadata": {
    "contentType": "application/did+json",
    "retrieved": "2023-10-19T00:19:19.091208+00:00",
    "error": "notVerified",
    "errorMessage": "The DID document could not be verified against the KERI event stream"
  },
  "didDocumentMetadata": {
    "witnesses": [
      {
        "idx": 0,
        "scheme": "http",
        "url": "http://witnesshost:5642/"
      },
      {
        "idx": 0,
        "scheme": "tcp",
        "url": "tcp://witnesshost:5632/"
      },
      {
        "idx": 1,
        "scheme": "http",
        "url": "http://witnesshost:5643/"
      },
      {
        "idx": 1,
        "scheme": "tcp",
        "url": "tcp://witnesshost:5633/"
      },
      {
        "idx": 2,
        "scheme": "http",
        "url": "http://witnesshost:5644/"
      },
      {
        "idx": 2,
        "scheme": "tcp",
        "url": "tcp://witnesshost:5634/"
      }
    ],
    "versionId": "0",
    "didDocUrl": "http://raw.githubusercontent.com/WebOfTrust/WOT-terms/main/docs/test/did-webs-iiw37-tutorial/EP1NLexo6s8Fk1R_jwOoUd24JN9DWVmF41xrJFpb8aBR/did.json",
    "keriCesrUrl": "http://raw.githubusercontent.com/WebOfTrust/WOT-terms/main/docs/test/did-webs-iiw37-tutorial/EP1NLexo6s8Fk1R_jwOoUd24JN9DWVmF41xrJFpb8aBR/keri.cesr"
  }
}
bash-5.1#

**Comment by peacekeeper** [comment]
Great, thanks for your input and patience!
