### ISSUE TITLE
Check Uniresolver resolves the right way

### ISSUE THREAD

**Issue by henkvancann** [peacekeeper/did-webs-iiw-tutorial#8]
I went to the process once more with a new domain and path: blockchainbird.org:did-webs

https://dev.uniresolver.io/#did:webs:blockchainbird.org:did-webs:EG8GsKYdICKs-zI6odM6tvCmxRT2J-7UkZFqA77agtb8

en https://dev.uniresolver.io/#did:web:blockchainbird.org:did-webs:EG8GsKYdICKs-zI6odM6tvCmxRT2J-7UkZFqA77agtb8

I'm interested what you think of the results. 
JSON: right?
CESR: I do get  "[notFound] undefined" because the cesr file is no DID and needs to be locally verified using KLI?

**Comment by peacekeeper** [comment]
@henkvancann Great to see this with a new domain name!

If the DID is

```
did:webs:blockchainbird.org:did-webs:EG8GsKYdICKs-zI6odM6tvCmxRT2J-7UkZFqA77agtb8
```

then I would expect the files to be available here:

https://blockchainbird.org/did-webs/EG8GsKYdICKs-zI6odM6tvCmxRT2J-7UkZFqA77agtb8/did.json
https://blockchainbird.org/did-webs/EG8GsKYdICKs-zI6odM6tvCmxRT2J-7UkZFqA77agtb8/keri.cesr

But these return "Page not found"

**Comment by henkvancann** [comment]
Right, we made a very practical mistake uploading them to 
https://blockchainbird.org/did-webs/did.json
https://blockchainbird.org/did-webs/keri.cesr

(I'm doing this together with Kor, my colleague, he's interested in this stuff too because we'd like to have KERI SAID in the kerisse.org :) )

Will do it later tonight, have to go.

**Comment by henkvancann** [comment]
It's done and getting more results

**Comment by peacekeeper** [comment]
Nice!!!

**Comment by henkvancann** [comment]
Now I'm going to test rotation + validation
