### ISSUE TITLE
Check results after key rotation

### ISSUE THREAD

**Issue by henkvancann** [peacekeeper/did-webs-iiw-tutorial#9]
As far as I can see, everything functions as it should. This is the output of Resolving the AID locally as did:webs.:
```
Different values for key verificationMethod: [{'id': '#DPC9R0MjfZ4xlaFN3F-ONbUF82oGE8mRsO56djkgPe8_', 'type': 'JsonWebKey', 'controller': 'did:webs:blockchainbird.org:did-webs:EG8GsKYdICKs-zI6odM6tvCmxRT2J-7UkZFqA77agtb8', 'publicKeyJwk': {'kid': 'DPC9R0MjfZ4xlaFN3F-ONbUF82oGE8mRsO56djkgPe8_', 'kty': 'OKP', 'crv': 'Ed25519', 'x': '8L1HQyN9njGVoU3cX441tQXzagYTyZGw7np2OSA97z8'}}] (expected) vs. [{'id': '#DE66AOOkDd6QW09BrThLko37rZBd1dRcn2tgKYPEzWg5', 'type': 'JsonWebKey', 'controller': 'did:webs:blockchainbird.org:did-webs:EG8GsKYdICKs-zI6odM6tvCmxRT2J-7UkZFqA77agtb8', 'publicKeyJwk': {'kid': 'DE66AOOkDd6QW09BrThLko37rZBd1dRcn2tgKYPEzWg5', 'kty': 'OKP', 'crv': 'Ed25519', 'x': 'TroA46QN3pBbT0GtOEuSjfutkF3V1Fyfa2Apg8TNaDk'}}] (actual)
```
This is the full version of commands & output after rotation & resolving locally:

```
bash-5.1# kli list --name controller
controller (EG8GsKYdICKs-zI6odM6tvCmxRT2J-7UkZFqA77agtb8)
bash-5.1# kli status --name controller
Alias: 	controller
Identifier: EG8GsKYdICKs-zI6odM6tvCmxRT2J-7UkZFqA77agtb8
Seq No:	0

Witnesses:
Count:		3
Receipts:	3
Threshold:	3

Public Keys:	
	1. DE66AOOkDd6QW09BrThLko37rZBd1dRcn2tgKYPEzWg5

bash-5.1# kli rotate --name controller
usage: kli rotate [-h] --name NAME [--base BASE] --alias ALIAS [--passcode BRAN] [--file FILE] [--next-count NEXT_COUNT] [--receipt-endpoint] [--isith ISITH] [--nsith NSITH] [--toad TOAD] [--witnesses <prefix>]
                  [--witness-cut <prefix>] [--witness-add <prefix>] [--data DATA]
kli rotate: error: the following arguments are required: --alias/-a
bash-5.1# kli rotate --name controller --alias controllerR2
ERR: Alias controllerR2 is invalid
bash-5.1# kli rotate --name controller --alias controller
Waiting for witness receipts...
Prefix  EG8GsKYdICKs-zI6odM6tvCmxRT2J-7UkZFqA77agtb8
New Sequence No.  1
	Public key 1:  DPC9R0MjfZ4xlaFN3F-ONbUF82oGE8mRsO56djkgPe8_
bash-5.1# kli status --name controller
Alias: 	controller
Identifier: EG8GsKYdICKs-zI6odM6tvCmxRT2J-7UkZFqA77agtb8
Seq No:	1

Witnesses:
Count:		3
Receipts:	3
Threshold:	3

Public Keys:	
	1. DPC9R0MjfZ4xlaFN3F-ONbUF82oGE8mRsO56djkgPe8_

bash-5.1# dkr did webs resolve --name controller --did did:webs:blockchainbird.org:did-webs:EG8GsKYdICKs-zI6odM6tvCmxRT2J-7UkZFqA77agtb8
Loading DID Doc from http://blockchainbird.org/did-webs/EG8GsKYdICKs-zI6odM6tvCmxRT2J-7UkZFqA77agtb8/did.json
Loading KERI CESR from http://blockchainbird.org/did-webs/EG8GsKYdICKs-zI6odM6tvCmxRT2J-7UkZFqA77agtb8/keri.cesr
DID Doc does not verify
Comparing dictionaries:
expected:
{expected} 
and
 
actual:
{actual}
Comparing key id
Comparing key verificationMethod
Different values for key verificationMethod: [{'id': '#DPC9R0MjfZ4xlaFN3F-ONbUF82oGE8mRsO56djkgPe8_', 'type': 'JsonWebKey', 'controller': 'did:webs:blockchainbird.org:did-webs:EG8GsKYdICKs-zI6odM6tvCmxRT2J-7UkZFqA77agtb8', 'publicKeyJwk': {'kid': 'DPC9R0MjfZ4xlaFN3F-ONbUF82oGE8mRsO56djkgPe8_', 'kty': 'OKP', 'crv': 'Ed25519', 'x': '8L1HQyN9njGVoU3cX441tQXzagYTyZGw7np2OSA97z8'}}] (expected) vs. [{'id': '#DE66AOOkDd6QW09BrThLko37rZBd1dRcn2tgKYPEzWg5', 'type': 'JsonWebKey', 'controller': 'did:webs:blockchainbird.org:did-webs:EG8GsKYdICKs-zI6odM6tvCmxRT2J-7UkZFqA77agtb8', 'publicKeyJwk': {'kid': 'DE66AOOkDd6QW09BrThLko37rZBd1dRcn2tgKYPEzWg5', 'kty': 'OKP', 'crv': 'Ed25519', 'x': 'TroA46QN3pBbT0GtOEuSjfutkF3V1Fyfa2Apg8TNaDk'}}] (actual)
{
  "didDocument": null,
  "didResolutionMetadata": {
    "contentType": "application/did+json",
    "retrieved": "2023-10-24T12:37:02.710009+00:00",
    "error": "notVerified",
    "errorMessage": "The DID document could not be verified against the KERI event stream"
  },
  "didDocumentMetadata": {
    "witnesses": [
      {
        "idx": 0,
        "scheme": "http",
        "url": "http://witnesshost:5642/"
      },
      {
        "idx": 0,
        "scheme": "tcp",
        "url": "tcp://witnesshost:5632/"
      },
      {
        "idx": 1,
        "scheme": "http",
        "url": "http://witnesshost:5643/"
      },
      {
        "idx": 1,
        "scheme": "tcp",
        "url": "tcp://witnesshost:5633/"
      },
      {
        "idx": 2,
        "scheme": "http",
        "url": "http://witnesshost:5644/"
      },
      {
        "idx": 2,
        "scheme": "tcp",
        "url": "tcp://witnesshost:5634/"
      }
    ],
    "versionId": "1",
    "didDocUrl": "http://blockchainbird.org/did-webs/EG8GsKYdICKs-zI6odM6tvCmxRT2J-7UkZFqA77agtb8/did.json",
    "keriCesrUrl": "http://blockchainbird.org/did-webs/EG8GsKYdICKs-zI6odM6tvCmxRT2J-7UkZFqA77agtb8/keri.cesr"
  }
}
```

**Comment by henkvancann** [comment]
I will try and proceed updating the published .cesr file and then resolve again.

**Comment by peacekeeper** [comment]
Thanks for testing and trying out various steps, this is helpful!

**Comment by henkvancann** [comment]
> I will try and proceed updating the published .cesr file and then resolve again.

bash-5.1# dkr did webs resolve --name controller --did did:webs:blockchainbird.org:did-webs:EG8GsKYdICKs-zI6odM6tvCmxRT2J-7UkZFqA77agtb8
Loading DID Doc from http://blockchainbird.org/did-webs/EG8GsKYdICKs-zI6odM6tvCmxRT2J-7UkZFqA77agtb8/did.json
Loading KERI CESR from http://blockchainbird.org/did-webs/EG8GsKYdICKs-zI6odM6tvCmxRT2J-7UkZFqA77agtb8/keri.cesr
DID Doc verified
{
  "id": "did:webs:blockchainbird.org:did-webs:EG8GsKYdICKs-zI6odM6tvCmxRT2J-7UkZFqA77agtb8",
  "verificationMethod": [
    {
      "id": "#DPC9R0MjfZ4xlaFN3F-ONbUF82oGE8mRsO56djkgPe8_",
      "type": "JsonWebKey",
      "controller": "did:webs:blockchainbird.org:did-webs:EG8GsKYdICKs-zI6odM6tvCmxRT2J-7UkZFqA77agtb8",
      "publicKeyJwk": {
        "kid": "DPC9R0MjfZ4xlaFN3F-ONbUF82oGE8mRsO56djkgPe8_",
        "kty": "OKP",
        "crv": "Ed25519",
        "x": "8L1HQyN9njGVoU3cX441tQXzagYTyZGw7np2OSA97z8"
      }
    }
  ]
}

After re-generating locally in the container the did.json and keri.cesr were overwritten. I uploaded them:
http://blockchainbird.org/did-webs/EG8GsKYdICKs-zI6odM6tvCmxRT2J-7UkZFqA77agtb8/did.json
You can compare with the original one before rotating the keys:
http://blockchainbird.org/did-webs/EG8GsKYdICKs-zI6odM6tvCmxRT2J-7UkZFqA77agtb8/did.json_old

http://blockchainbird.org/did-webs/EG8GsKYdICKs-zI6odM6tvCmxRT2J-7UkZFqA77agtb8/keri.cesr
You can compare with the original one before rotating the keys:
http://blockchainbird.org/did-webs/EG8GsKYdICKs-zI6odM6tvCmxRT2J-7UkZFqA77agtb8/keri.cesr_old

**Comment by henkvancann** [comment]
The Universal resolver worked fine after rotation and showed the rotated public key:
<img width="912" alt="Screenshot 2023-10-25 at 01 13 41" src="https://github.com/peacekeeper/did-webs-iiw37-tutorial/assets/479356/9df15c42-8961-418d-bca5-e1a60d490c88">

And expectedly this resolved well too:

bash-5.1# dkr did keri resolve --name controller --did did:keri:EG8GsKYdICKs-zI6odM6tvCmxRT2J-7UkZFqA77agtb8 --oobi http://witnesshost:5642/oobi/EG8GsKYdICKs-zI6odM6tvCmxRT2J-7UkZFqA77agtb8/witness/BBilc4-L3tFUnfM_wJr4S4OJanAv_VmF_dJNN6vkf2Ha
From arguments got aid: EG8GsKYdICKs-zI6odM6tvCmxRT2J-7UkZFqA77agtb8
From arguments got oobi: http://witnesshost:5642/oobi/EG8GsKYdICKs-zI6odM6tvCmxRT2J-7UkZFqA77agtb8/witness/BBilc4-L3tFUnfM_wJr4S4OJanAv_VmF_dJNN6vkf2Ha
{
  "id": "did:keri:EG8GsKYdICKs-zI6odM6tvCmxRT2J-7UkZFqA77agtb8",
  "verificationMethod": [
    {
      "id": "#DPC9R0MjfZ4xlaFN3F-ONbUF82oGE8mRsO56djkgPe8_",
      "type": "JsonWebKey",
      "controller": "did:keri:EG8GsKYdICKs-zI6odM6tvCmxRT2J-7UkZFqA77agtb8",
      "publicKeyJwk": {
        "kid": "DPC9R0MjfZ4xlaFN3F-ONbUF82oGE8mRsO56djkgPe8_",
        "kty": "OKP",
        "crv": "Ed25519",
        "x": "8L1HQyN9njGVoU3cX441tQXzagYTyZGw7np2OSA97z8"
      }
    }
  ]
}

**Comment by henkvancann** [comment]
These are the differences between the old and the new published files after rotation:

JSON (RED = NEW)

<img width="1120" alt="Screenshot 2023-10-25 at 01 22 12" src="https://github.com/peacekeeper/did-webs-iiw37-tutorial/assets/479356/ed040b28-73bd-46f0-937f-37751ae2c089">

CESR (RED = NEW) Unfortunately my free web diff tool isn't too smart on this one ->

<img width="1301" alt="Screenshot 2023-10-25 at 01 30 24" src="https://github.com/peacekeeper/did-webs-iiw37-tutorial/assets/479356/a4e83498-4fae-46d6-a1cf-712b3af1be2e">
